#########################
# iVAE on climate
#########################

ROOT: 'data/climate'
LOG: 'baseline/results/ivae_climate'
DATASET: 'prepared_screened'

NS: TRUE
MODEL: 'iVAE'

VAE:
    GPU: [0]
    CPU: 4
    TRAIN_BS: 32
    VAL_BS: 256
    EPOCHS: 200
    N_VAL_SAMPLES: 64
    INPUT_DIM: 47
    LATENT_DIM: 7
    ENC:
        HIDDEN_DIM: 128
    DEC:
        HIDDEN_DIM: 128
    PIN: TRUE

iVAE:
    LR: 1.0e-3

MCC:
    FREQ: 0.1
    CORR: 'Pearson'
